// Crazy-tab analytics. Eight metrics that turn raw JSONL session
// transcripts into uncomfortably honest charts. Every function returns
// plain JSON and reads only from the local SQLite DB, no external
// services. Heavy queries memoize via metric-cache if needed; for now
// they all run in <200ms on a ~200K-event corpus.
import fs from "node:fs";
import path from "node:path";
import { SqlBatch, queryRows, sha256, sqlString } from "./sqlite.js";

// — Shared helpers ────────────────────────────────────────────────────

// Words/phrases the user types AFTER an assistant turn when the
// previous answer didn't land. Two classes: polite corrections (no,
// wrong, actually) and explicit frustration (fuck, wtf, ugh). We
// match both, but the fingerprint surfaces the top-by-count so
// the spicy ones show up if they're really how you talk.
const CORRECTION_RE =
  /\b(no|nope|wrong|actually|instead|that'?s not|try again|undo|revert|broken|fix this|redo|start over|didn'?t (?:work|finish|complete)|stop|don'?t|why (?:did|are) you|fuck|fucks?|fucking|shit|damn|hell|wtf|dammit|bullshit|bs|crap|ugh|jesus|christ|wtaf|smh|wth|frustrat\w*|annoying|stupid|come on|seriously|bruh)\b/i;

// Phrases the model says when it's stalling / over-apologizing /
// performing competence rather than demonstrating it. The literature
// calls this "obsequiousness" and "sycophancy"; we just call it the
// pep-talk index.
const PEPTALK_RE =
  /\b(great question|good (?:question|catch|point)|excellent|absolutely|i see what'?s happening|i understand|let me (?:help|fix|investigate)|i'?ll (?:fix|help|investigate|take a look)|perfect|exactly|happy to|of course|great idea|that makes sense)\b/i;

function parseRaw(json) {
  try { return JSON.parse(json); } catch { return null; }
}

// ─── Learned noise cache ──────────────────────────────────────────────
//
// We persist a per-user blacklist of agent-brief phrases in `summaries`
// (kind='learned_noise_phrases'). Refreshed on every sync; consumed by
// aiFingerprint at phrase-mining time. The dashboard ships with zero
// hardcoded project-specific terms; everything domain-specific is
// learned from the user's own corpus.
const LEARNED_NOISE_KIND = "learned_noise_phrases";
const LEARNED_NOISE_KEY = sha256(`${LEARNED_NOISE_KIND}:v1`);

export function loadLearnedNoise() {
  try {
    const rows = queryRows(
      `SELECT payload FROM summaries WHERE content_hash = ${sqlString(LEARNED_NOISE_KEY)} LIMIT 1`
    );
    if (!rows.length) return [];
    const parsed = JSON.parse(rows[0].payload);
    return Array.isArray(parsed.phrases) ? parsed.phrases.map((p) => p.phrase) : [];
  } catch {
    return [];
  }
}

/**
 * Compute and persist the user-specific noise-phrase blacklist.
 *
 * For each bigram/trigram in the user's messages, compute its frequency
 * in LONG messages (>500 chars, agent briefs / instructions) vs SHORT
 * messages (<=500 chars, conversational). A phrase that's dramatically
 * more common in long messages is "instruction language" for this user
 * and should be filtered out of the favorite-phrases list. A phrase
 * common in BOTH or only in short messages is real voice — keep it.
 *
 * Stable across users: the algorithm has no hardcoded domain terms.
 * Whatever a user's projects involve, the long-message corpus reveals
 * their boilerplate.
 */
export function learnNoisePhrases({ topN = 300, minLongCount = 3, minRatio = 3 } = {}) {
  const userMsgs = queryRows(`
    SELECT raw_json FROM raw_events
    WHERE payload_type IN ('user_message', 'user') OR event_type = 'user'
    LIMIT 20000
  `);
  // Same skip rules aiFingerprint uses, kept inline so the learner is
  // self-contained and doesn't depend on the calling order.
  const META_RE = /The following is the Codex agent history|>>> TRANSCRIPT START|^\s*\[Request interrupted by user|Caveat: The messages below were generated by the user while running local commands|^\s*<command-caveat>|^\s*<system-reminder>|^\s*<task-notification>|^\s*<command-name>|^\s*<command-message>|^\s*\[Image:?\s*source:|^\s*\[Image\s*\d*\s*:|^\s*\[Pasted text/i;
  const longCounts = new Map();
  const shortCounts = new Map();
  let longMessages = 0;
  let shortMessages = 0;
  for (const m of userMsgs) {
    const raw = extractMessageText(m, { userOnly: true });
    if (!raw || META_RE.test(raw)) continue;
    // Strip Codex IDE context: real ask after "## My request" if present.
    let text = raw;
    const marker = text.indexOf("## My request");
    if (marker >= 0) {
      text = text.slice(marker).replace(/^##\s+My request[^\n]*\n+/, "");
    } else {
      // No "## My request" marker: still strip Open tabs + In app
      // browser blocks because their bullets ("- # 12 - Self-Running
      // Feature Loop: ...") leak filename fragments otherwise.
      let inTabs = false, inBrowser = false;
      text = text
        .split("\n")
        .filter((line) => {
          const t = line.trim();
          if (!t) { inTabs = false; inBrowser = false; return true; }
          if (/^#{1,6}\s/.test(t)) {
            inTabs = /open tabs/i.test(t);
            inBrowser = /in app browser/i.test(t);
            return false;
          }
          if ((inTabs || inBrowser) && /^[-*]\s/.test(t)) return false;
          if (/^[-*]\s+\S+\.\w+:\s+\S+/.test(t)) return false;
          return true;
        })
        .join("\n");
    }
    if (!text) continue;

    const isLong = text.length > 500;
    if (isLong) longMessages++;
    else shortMessages++;

    const words = text
      .toLowerCase()
      .replace(/```[\s\S]*?```/g, " ")
      .replace(/`[^`]*`/g, " ")
      .replace(/https?:\/\/\S+/g, " ")
      .replace(/\S+\/\S+/g, " ")
      .replace(/&[a-z]+;/g, " ")
      .replace(/[^a-z0-9\s']/g, " ")
      .split(/\s+/)
      .filter((w) => w.length >= 2 && w.length <= 20)
      .filter((w) => {
        if (/^\d+$/.test(w)) return false;
        if (w.length >= 6 && /\d/.test(w) && /[a-z]/.test(w)) return false;
        return true;
      });
    const target = isLong ? longCounts : shortCounts;
    for (let i = 0; i + 1 < words.length; i++) {
      const key2 = `${words[i]} ${words[i + 1]}`;
      target.set(key2, (target.get(key2) || 0) + 1);
      if (i + 2 < words.length) {
        const key3 = `${words[i]} ${words[i + 1]} ${words[i + 2]}`;
        target.set(key3, (target.get(key3) || 0) + 1);
      }
    }
  }
  // Need both pools to compute a ratio. If user only has long messages
  // (rare; maybe they only write agent briefs), bail with empty list.
  if (longMessages === 0 || shortMessages === 0) {
    return persistLearnedNoise([], { longMessages, shortMessages });
  }
  // Score: per-message frequency in long vs short. We want phrases
  // that occur in many long messages but are absent or rare in short.
  // Add Laplace smoothing so phrases unseen in short don't divide by 0.
  const scored = [];
  for (const [phrase, longC] of longCounts) {
    if (longC < minLongCount) continue;
    const shortC = shortCounts.get(phrase) || 0;
    const longRate = longC / longMessages;
    const shortRate = (shortC + 1) / (shortMessages + 1); // smoothed
    const ratio = longRate / shortRate;
    if (ratio < minRatio) continue;
    scored.push({ phrase, longC, shortC, ratio: Number(ratio.toFixed(2)) });
  }
  // Union of two sorts:
  //  - by ratio (catches rare-but-pure instruction phrases like "spec
  //    doc" that the user never says conversationally)
  //  - by raw long-message count (catches high-volume phrases like
  //    "the user" that ALSO show up in short messages occasionally,
  //    so their ratio is "only" ~15 but they're still 90% noise).
  // Without the volume cut, very common instruction words get pushed
  // out of the top-N by long-tail rare phrases.
  const byRatio = [...scored].sort((a, b) => b.ratio - a.ratio || b.longC - a.longC);
  const byVolume = [...scored].sort((a, b) => b.longC - a.longC || b.ratio - a.ratio);
  const seen = new Set();
  const learned = [];
  const halfN = Math.ceil(topN / 2);
  for (const p of byRatio.slice(0, halfN)) {
    if (!seen.has(p.phrase)) { seen.add(p.phrase); learned.push(p); }
  }
  for (const p of byVolume.slice(0, halfN)) {
    if (!seen.has(p.phrase)) { seen.add(p.phrase); learned.push(p); }
  }
  return persistLearnedNoise(learned, { longMessages, shortMessages });
}

function persistLearnedNoise(phrases, meta) {
  const payload = {
    generated_at: new Date().toISOString(),
    long_messages: meta.longMessages || 0,
    short_messages: meta.shortMessages || 0,
    phrases,
  };
  const batch = new SqlBatch();
  batch.add(
    `INSERT OR REPLACE INTO summaries (content_hash, kind, model, generated_at, payload)
     VALUES (${sqlString(LEARNED_NOISE_KEY)}, ${sqlString(LEARNED_NOISE_KIND)}, NULL,
             ${sqlString(payload.generated_at)},
             ${sqlString(JSON.stringify(payload))})`
  );
  batch.flush();
  return payload;
}

// Pulls the textual body out of a raw_events row, regardless of which
// JSONL flavor (Codex's nested payload, Claude's message.content array).
// `userOnly` mode rejects tool_result wrappers Claude stores with
// type=user but which are actually the model receiving tool output,
// not the human typing.
function extractMessageText(row, opts = {}) {
  const j = parseRaw(row.raw_json);
  if (!j) return "";
  // Codex shape: {type: "event_msg", payload: {type: "user_message", message: "..."}}
  if (j.payload?.message && typeof j.payload.message === "string") return j.payload.message;
  // Claude shape: {message: {content: [{type: "text", text: "..."}]}}
  if (Array.isArray(j.message?.content)) {
    const items = j.message.content;
    // Claude tool_result wrapper: pseudo-user message whose content
    // is the tool output. Not user voice; skip when caller asks for
    // userOnly. We detect by presence of any tool_result child.
    if (opts.userOnly && items.some((p) => p?.type === "tool_result")) return "";
    return items
      .filter((p) => p?.type === "text" && typeof p.text === "string")
      .map((p) => p.text)
      .join("\n");
  }
  if (typeof j.message?.content === "string") return j.message.content;
  // Claude assistant shape: top-level content array
  if (Array.isArray(j.content)) {
    return j.content
      .filter((p) => p?.type === "text" && typeof p.text === "string")
      .map((p) => p.text)
      .join("\n");
  }
  return "";
}

function hourFromIso(iso) {
  if (!iso) return null;
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return null;
  return d.getHours();
}

// — #2: Frustration curve (hour of day) ───────────────────────────────
//
// For each user message, hour-bucket the timestamp and flag if it
// contains a correction phrase. Output the correction-rate per hour
// so the user can see when in the day they push back the hardest.
export function frustrationByHour() {
  const rows = queryRows(`
    SELECT timestamp, raw_json
    FROM raw_events
    WHERE payload_type IN ('user_message', 'user')
       OR event_type = 'user'
    ORDER BY timestamp
  `);
  const buckets = Array.from({ length: 24 }, () => ({ total: 0, frustrated: 0 }));
  for (const r of rows) {
    const h = hourFromIso(r.timestamp);
    if (h == null) continue;
    buckets[h].total++;
    const text = extractMessageText(r);
    if (text && CORRECTION_RE.test(text)) buckets[h].frustrated++;
  }
  return {
    by_hour: buckets.map((b, h) => ({
      hour: h,
      total: b.total,
      frustrated: b.frustrated,
      rate: b.total > 0 ? b.frustrated / b.total : 0,
    })),
    total_messages: rows.length,
    total_frustrated: buckets.reduce((a, b) => a + b.frustrated, 0),
  };
}

// — #5: Cost per LOC kept (approximation) ─────────────────────────────
//
// For each cwd, sum the spend across turns that wrote there, divide by
// the current LOC of source files in that repo. Imperfect (counts cost
// that produced no code, ignores deleted lines, doesn't track AI vs
// human authorship line by line), but the ratio still surfaces the
// repos where you spent a fortune and have little to show.
function repoLineCount(cwd) {
  if (!cwd || !fs.existsSync(cwd)) return 0;
  // Only count source files we recognize, skip node_modules/.git/etc.
  // Bounded depth + extension whitelist keeps this snappy.
  const EXT = new Set([
    ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs",
    ".py", ".go", ".rs", ".java", ".kt", ".swift",
    ".rb", ".php", ".c", ".cc", ".cpp", ".h", ".hpp",
    ".cs", ".scala", ".lua", ".sh", ".sql",
    ".html", ".css", ".scss", ".vue", ".svelte",
  ]);
  const SKIP = new Set(["node_modules", ".git", "dist", "build", ".next", "vendor", "target", ".venv", "__pycache__"]);
  let lines = 0;
  function walk(dir, depth) {
    if (depth > 8) return;
    let entries;
    try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return; }
    for (const e of entries) {
      if (SKIP.has(e.name)) continue;
      const full = path.join(dir, e.name);
      if (e.isDirectory()) {
        walk(full, depth + 1);
      } else if (EXT.has(path.extname(e.name))) {
        try {
          const data = fs.readFileSync(full, "utf8");
          lines += data.split("\n").length;
        } catch { /* unreadable, skip */ }
      }
    }
  }
  walk(cwd, 0);
  return lines;
}

export function costPerLOCKept(limit = 12) {
  const rows = queryRows(`
    SELECT t.cwd,
           COUNT(DISTINCT t.turn_id) AS turns,
           SUM(COALESCE(tu.input_tokens,0) + COALESCE(tu.output_tokens,0)
               + COALESCE(tu.reasoning_output_tokens,0)) AS billable_tokens
    FROM turns t
    LEFT JOIN token_usage tu ON tu.turn_id = t.turn_id
    WHERE t.cwd IS NOT NULL AND t.cwd <> ''
    GROUP BY t.cwd
    HAVING turns > 5
    ORDER BY billable_tokens DESC
    LIMIT ${limit}
  `);
  // Use the same crude $/MTok approximation cost-overview uses for
  // rough cost. We could pull pricing.js for per-model rates but the
  // ratio is what matters here, not absolute dollar accuracy.
  const ROUGH_USD_PER_MTOK = 8;
  return rows.map((r) => {
    const tokens = Number(r.billable_tokens || 0);
    const usd = (tokens / 1_000_000) * ROUGH_USD_PER_MTOK;
    const loc = repoLineCount(r.cwd);
    return {
      cwd: r.cwd,
      cwd_short: r.cwd.replace(/^.*?\/([^/]+\/[^/]+)$/, "$1"),
      turns: Number(r.turns),
      tokens,
      cost: usd,
      loc,
      cost_per_loc: loc > 0 ? usd / loc : null,
      exists: loc > 0,
    };
  });
}

// — #6: Context-broke-the-camel's-back ────────────────────────────────
//
// For each session, walk turns in order, accumulate billable tokens.
// For each turn, check if the very next user message contains a
// correction. Bucket turns by cumulative-token band and report the
// correction-rate per band. Reveals at what context length the model's
// answers stop landing for you.
export function contextDegradationCurve() {
  const turns = queryRows(`
    SELECT t.turn_id, t.session_id, t.started_at, t.source,
           COALESCE(tu.input_tokens,0) + COALESCE(tu.output_tokens,0)
             + COALESCE(tu.reasoning_output_tokens,0) AS toks
    FROM turns t
    LEFT JOIN token_usage tu ON tu.turn_id = t.turn_id
    WHERE t.session_id IS NOT NULL AND t.started_at IS NOT NULL
    ORDER BY t.session_id, t.started_at
  `);
  const userMsgs = queryRows(`
    SELECT timestamp, raw_json, source
    FROM raw_events
    WHERE payload_type IN ('user_message', 'user') OR event_type = 'user'
    ORDER BY timestamp
  `);
  // Sort user msgs into per-session timelines via source_path proximity.
  // We index by timestamp and scan for "is there a frustrated user msg
  // within 5 minutes after the turn ended". Cheap and good enough.
  const corrTimes = [];
  for (const m of userMsgs) {
    if (!m.timestamp) continue;
    const text = extractMessageText(m);
    if (text && CORRECTION_RE.test(text)) {
      corrTimes.push(new Date(m.timestamp).getTime());
    }
  }
  corrTimes.sort((a, b) => a - b);
  function hasCorrectionShortlyAfter(iso) {
    if (!iso) return false;
    const start = new Date(iso).getTime();
    if (Number.isNaN(start)) return false;
    // Binary search the lower bound, then scan forward.
    let lo = 0, hi = corrTimes.length;
    while (lo < hi) {
      const mid = (lo + hi) >>> 1;
      if (corrTimes[mid] < start) lo = mid + 1; else hi = mid;
    }
    const t = corrTimes[lo];
    return t != null && t - start < 5 * 60 * 1000;
  }

  // Per-session cumulative.
  let lastSession = null;
  let cumulative = 0;
  const BUCKETS = [
    [0, 10_000, "0-10k"],
    [10_000, 25_000, "10-25k"],
    [25_000, 50_000, "25-50k"],
    [50_000, 100_000, "50-100k"],
    [100_000, 200_000, "100-200k"],
    [200_000, Infinity, "200k+"],
  ];
  const out = BUCKETS.map(([, , label]) => ({ band: label, turns: 0, corrected: 0, rate: 0 }));
  for (const t of turns) {
    if (t.session_id !== lastSession) {
      lastSession = t.session_id;
      cumulative = 0;
    }
    cumulative += Number(t.toks || 0);
    const idx = BUCKETS.findIndex(([lo, hi]) => cumulative >= lo && cumulative < hi);
    if (idx < 0) continue;
    out[idx].turns++;
    if (hasCorrectionShortlyAfter(t.started_at)) out[idx].corrected++;
  }
  out.forEach((b) => { b.rate = b.turns > 0 ? b.corrected / b.turns : 0; });
  return { by_band: out };
}

// — #8: Phantom edit graveyard ────────────────────────────────────────
//
// Files Claude/Codex wrote that don't exist on disk anymore. Either
// you renamed them, you deleted them in disgust, or the AI hallucinated
// the path. The query pulls Edit/Write/apply_patch tool calls and the
// loop just stat()s each unique target.
export function phantomEdits(limit = 50) {
  const rows = queryRows(`
    SELECT tool_name, command, status, cwd, turn_id, source
    FROM tool_events
    WHERE tool_name IN ('Edit', 'Write', 'apply_patch')
       OR tool_name = 'MultiEdit'
    ORDER BY rowid DESC
    LIMIT 5000
  `);
  // Extract file_path from tool command JSON (Claude) or unified diff
  // body (Codex apply_patch). Keep it best-effort.
  function pathFromCommand(toolName, command) {
    if (!command) return null;
    // Claude Edit/Write/MultiEdit: command is JSON-ish args text.
    try {
      const j = JSON.parse(command);
      if (j.file_path) return j.file_path;
      if (j.path) return j.path;
    } catch { /* not JSON, keep going */ }
    // Codex apply_patch: look for "*** Update File:" / "*** Add File:"
    const m = command.match(/\*\*\*\s+(?:Update|Add|Delete)\s+File:\s+(\S+)/);
    if (m) return m[1];
    return null;
  }
  const seen = new Map();
  for (const r of rows) {
    const p = pathFromCommand(r.tool_name, r.command);
    if (!p) continue;
    const abs = path.isAbsolute(p) ? p : (r.cwd ? path.join(r.cwd, p) : p);
    if (seen.has(abs)) {
      const e = seen.get(abs);
      e.edits++;
    } else {
      seen.set(abs, {
        path: abs,
        cwd: r.cwd || null,
        edits: 1,
        last_source: r.source,
      });
    }
  }
  const out = [];
  for (const entry of seen.values()) {
    let exists = false;
    try { exists = fs.existsSync(entry.path); } catch { exists = false; }
    if (!exists) out.push(entry);
  }
  out.sort((a, b) => b.edits - a.edits);
  return out.slice(0, limit);
}

// — #9: Tool-call transitions (Sankey-ish) ────────────────────────────
//
// Sequential tool calls within the same turn, paired up: tool_i ->
// tool_{i+1}. Top N pairs by frequency surface your real workflows
// (Read -> Edit -> Bash is iterating; Read -> Read -> Read is wandering).
export function toolTransitions(limit = 15) {
  const rows = queryRows(`
    SELECT turn_id, tool_name
    FROM tool_events
    WHERE turn_id IS NOT NULL AND tool_name IS NOT NULL
    ORDER BY turn_id, rowid
  `);
  const counts = new Map();
  let lastTurn = null;
  let lastTool = null;
  for (const r of rows) {
    if (r.turn_id !== lastTurn) {
      lastTurn = r.turn_id;
      lastTool = null;
    }
    if (lastTool) {
      const key = `${lastTool}→${r.tool_name}`;
      counts.set(key, (counts.get(key) || 0) + 1);
    }
    lastTool = r.tool_name;
  }
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, limit)
    .map(([k, v]) => {
      const [from, to] = k.split("→");
      return { from, to, count: v };
    });
}

// — #18: Pep-talk index ───────────────────────────────────────────────
//
// How often the assistant says encouraging-but-empty things, and
// whether those sessions ended in user corrections. High pep-talk +
// high correction rate is the model bullshitting.
export function pepTalkIndex() {
  const rows = queryRows(`
    SELECT timestamp, raw_json, source
    FROM raw_events
    WHERE payload_type = 'assistant' OR event_type = 'assistant'
    ORDER BY timestamp
    LIMIT 10000
  `);
  let total = 0;
  let pepCount = 0;
  const topPhrases = new Map();
  for (const r of rows) {
    const text = extractMessageText(r);
    if (!text) continue;
    total++;
    const matches = text.match(new RegExp(PEPTALK_RE.source, "gi"));
    if (matches && matches.length > 0) {
      pepCount++;
      for (const m of matches) {
        const norm = m.toLowerCase().trim();
        topPhrases.set(norm, (topPhrases.get(norm) || 0) + 1);
      }
    }
  }
  return {
    total_assistant_msgs: total,
    pep_msgs: pepCount,
    rate: total > 0 ? pepCount / total : 0,
    top_phrases: [...topPhrases.entries()]
      .sort((a, b) => b[1] - a[1])
      .slice(0, 10)
      .map(([phrase, count]) => ({ phrase, count })),
  };
}

// — #21: AI fingerprint ───────────────────────────────────────────────
//
// One-page personality profile. Aggregates the existing tables into
// "things that would feel uncomfortably specific if a coworker said
// them about you".
export function aiFingerprint() {
  const topModel = queryRows(`
    SELECT model, COUNT(*) AS n
    FROM turns
    WHERE model IS NOT NULL AND model <> ''
    GROUP BY model
    ORDER BY n DESC
    LIMIT 3
  `);
  const peakHour = queryRows(`
    SELECT strftime('%H', started_at) AS h, COUNT(*) AS n
    FROM turns
    WHERE started_at IS NOT NULL
    GROUP BY h
    ORDER BY n DESC
    LIMIT 1
  `);
  const topProject = queryRows(`
    SELECT cwd, COUNT(*) AS n
    FROM turns
    WHERE cwd IS NOT NULL AND cwd <> ''
    GROUP BY cwd
    ORDER BY n DESC
    LIMIT 1
  `);
  const sessionStats = queryRows(`
    SELECT AVG(c) AS avg_turns
    FROM (SELECT COUNT(*) AS c FROM turns WHERE session_id IS NOT NULL GROUP BY session_id)
  `);

  // Scan user messages for: (a) most common short phrase you actually
  // say (bigrams + trigrams across all your prompts, minus stopwords);
  // (b) most common frustration token. Tool name stats were boring
  // because everyone's #1 is exec_command/Bash. Phrase stats are not.
  const userMsgs = queryRows(`
    SELECT raw_json FROM raw_events
    WHERE payload_type IN ('user_message', 'user') OR event_type = 'user'
    LIMIT 10000
  `);
  // Stopwords + ultra-short noise. Keep "you", "i", "can" as parts of
  // bigrams; we strip them only when they form the whole bigram.
  const STOP = new Set([
    "the","a","an","of","to","in","on","at","by","for","with","from","is","are","was","were",
    "be","been","being","do","does","did","this","that","these","those","it","its","as","if",
    "or","and","but","not","no","yes","so","just","very","too","also","then","than","there",
    "here","what","when","where","why","how","who","whom","which","my","me","mine","you","your",
    "yours","i","im","we","us","our","ours","he","him","his","she","her","hers","they","them",
    "their","theirs","com","de","la","el","et","un","une",
  ]);
  // Universal English connective tissue. Same for every speaker of
  // English, not user-specific. Pronoun + auxiliary + article filler.
  // This stays hardcoded.
  const PHRASE_BLACKLIST = new Set([
    "you can","i can","you are","i am","i was","it is","there is","there are",
    "this is","that is","you should","i should","you have","i have","i will","you will",
    "i think","you know","let me","let s","i d","you d","i ll","you ll",
    "for the","with the","without the","of the","to the","from the","on the","at the",
    "in the","by the","into the","via the","across the","through the","over the","under the",
    "as the","like the","than the","then the","we have","we need","we should","we want",
  ]);

  // User-specific learned noise. These phrases get auto-discovered by
  // comparing long-message frequency (agent briefs) to short-message
  // frequency (conversational). What's "instruction language" for one
  // user (e.g. "the migration agent" for a refactor-heavy user) is
  // totally different for another (e.g. "the react component" for a
  // frontend user). Reloaded per-sync from the summaries cache.
  const learnedNoise = loadLearnedNoise();
  for (const phrase of learnedNoise) PHRASE_BLACKLIST.add(phrase);
  const bigramCounts = new Map();
  const trigramCounts = new Map();
  const frustrationCounts = new Map();
  // Codex prepends IDE context to every user_message: a markdown block
  // ("# Context from my IDE setup", "## Active file:", "## Open tabs",
  // file path listings). That stuff isn't user voice. Strip it out
  // before n-gramming, otherwise the top phrase is just file path
  // components from your project tree.
  function stripIdeContext(text) {
    // Codex pattern: when the message starts with auto-injected
    // context blocks ("# Context from my IDE setup", "# In app
    // browser", "## Active file:"), the real ask lives after
    // "## My request for Codex:". Take only that tail.
    const codexMarker = text.indexOf("## My request");
    if (codexMarker >= 0) {
      const after = text.slice(codexMarker).replace(/^##\s+My request[^\n]*\n+/, "");
      return after;
    }
    // If we see context markers but no "## My request" tail, the
    // entire message is context — drop it. Counting bullets like
    // "- The user has the in-app browser open" as user voice would
    // poison the top-phrase signal.
    if (/^\s*#\s+(?:Context from|In app browser|Active file)/im.test(text)) return "";
    // Otherwise drop lines that look like context: paths, headers,
    // tab listings (any bullet inside a "## Open tabs:" block, even
    // when the filename has no extension like "# 12 - Self-Running
    // Feature Loop"). We track whether we're inside an Open tabs
    // block and drop ALL bullets until a blank line or next header.
    let inOpenTabs = false;
    let inInAppBrowser = false;
    return text
      .split("\n")
      .filter((line) => {
        const t = line.trim();
        if (!t) {
          inOpenTabs = false;
          inInAppBrowser = false;
          return true;
        }
        if (/^#{1,6}\s/.test(t)) {
          inOpenTabs = /open tabs/i.test(t);
          inInAppBrowser = /in app browser/i.test(t);
          return false;  // headers themselves are always context
        }
        if (inOpenTabs && /^[-*]\s/.test(t)) return false;     // tab bullet
        if (inInAppBrowser && /^[-*]\s/.test(t)) return false; // browser bullet
        if (/^[-*]\s+\S+\.\w+:\s+\S+/.test(t)) return false;   // "- file.ts: src/x.ts" tab listing
        if (/^\/Users\//.test(t) || /^\/home\//.test(t)) return false; // bare path
        return true;
      })
      .join("\n");
  }

  // Heuristics to keep ONLY the user's conversational voice:
  // - Agent briefs are usually 500+ chars with markdown headers
  //   like "# Mission", "# Task", "You are the X Agent". The user
  //   typed them, but they're instruction-language, not natural
  //   speech. Bias the n-gram pool toward shorter messages.
  // - Frustration tokens still count from any length (you swear in
  //   long messages too), so we apply the length filter ONLY to
  //   the phrase-mining loop, not the frustration loop.
  const AGENT_BRIEF_RE =
    /^\s*#\s+(?:Mission|Task|Goal|Objective|Plan|Brief|Instructions?|Workflow)\b|^You are\s+(?:evaluating|reviewing|helping|assessing|analyzing|building|writing|designing|the\s|an?\s|my\s|now\s|going\s|asked|tasked|expected|required|responsible)|^Your\s+(?:job|task|goal|mission|role|responsibility)\b|^\s*##\s+(?:Cwd|What'?s already done|Mission|Out of scope)|^You will see\b|^You'?ll see\b/im;
  // Claude Code's bracketed system markers stored as user_message
  // when the user hits Ctrl-C or pastes from the model. Not voice.
  const SYSTEM_MARKER_RE =
    /^\s*\[Request interrupted by user|^\s*\[?Caveat:\s*The messages|Caveat: The messages below were generated by the user while running local commands|^\s*<command-caveat>|^\s*<system-reminder>|^\s*<task-notification>|^\s*<command-name>|^\s*<command-message>|^\s*\[Image:?\s*source:|^\s*\[Image\s*\d*\s*:|^\s*\[Pasted text/i;

  for (const m of userMsgs) {
    const rawText = extractMessageText(m, { userOnly: true });
    if (!rawText) continue;
    // Codex auto-review wraps the whole previous transcript inside a
    // user_message ("The following is the Codex agent history...
    // >>> TRANSCRIPT START"). That's machine-generated meta-prompt
    // content, not your voice. Skip the entire message.
    if (
      /The following is the Codex agent history/i.test(rawText) ||
      />>> TRANSCRIPT START/i.test(rawText) ||
      SYSTEM_MARKER_RE.test(rawText)
    ) continue;
    const text = stripIdeContext(rawText);
    if (!text) continue;
    // Frustration: keep counting individual matches by lemma.
    const frust = text.match(new RegExp(CORRECTION_RE.source, "gi"));
    if (frust) for (const x of frust) {
      const norm = x.toLowerCase().trim();
      frustrationCounts.set(norm, (frustrationCounts.get(norm) || 0) + 1);
    }
    // Phrase mining: only on conversational messages. Skip agent
    // briefs (long messages, role-assignment markers). Frustration
    // already counted above regardless of length.
    if (text.length > 500) continue;
    if (AGENT_BRIEF_RE.test(text)) continue;
    // Phrase mining: split into words, generate 2- and 3-grams, drop
    // anything where the boundary words are both stopwords (those are
    // basically connective tissue, not your "voice").
    const words = text
      .toLowerCase()
      .replace(/```[\s\S]*?```/g, " ")  // strip code blocks (massive false-positive source)
      .replace(/`[^`]*`/g, " ")          // inline code
      .replace(/https?:\/\/\S+/g, " ")    // URLs
      .replace(/\S+\/\S+/g, " ")          // anything with a slash (paths)
      .replace(/&[a-z]+;/g, " ")          // html entities (&gt; -> "gt")
      .replace(/[^a-z0-9\s']/g, " ")
      .split(/\s+/)
      .filter((w) => w.length >= 1 && w.length <= 20)
      // Drop pure-numeric tokens and hex-ish tokens (git hashes,
      // commit refs leak through as "index 6aeyk..."). Threshold:
      // mixed alphanumeric of length >=6 with >=2 digits = probably
      // a hash. Real english words almost never look like that.
      .filter((w) => {
        if (/^\d+$/.test(w)) return false;
        // Any mixed alphanumeric of length >= 6 is overwhelmingly
        // a hash, commit ref, build id, or session id. Real english
        // tokens that mix letters and digits at that length (ipv6,
        // utf8, sha256) are rare and not phrase-y anyway.
        if (w.length >= 6 && /\d/.test(w) && /[a-z]/.test(w)) return false;
        return true;
      });
    for (let i = 0; i + 1 < words.length; i++) {
      const a = words[i], b = words[i + 1];
      // Both stop -> connective tissue. One stop is fine ("the file").
      if (STOP.has(a) && STOP.has(b)) continue;
      // Single-letter tokens or numbers are noise.
      if (a.length < 2 || b.length < 2) continue;
      const key = `${a} ${b}`;
      if (PHRASE_BLACKLIST.has(key)) continue;
      bigramCounts.set(key, (bigramCounts.get(key) || 0) + 1);
      if (i + 2 < words.length) {
        const c = words[i + 2];
        if (c.length >= 2) {
          // Trigram: skip if every word is a stopword.
          if (STOP.has(a) && STOP.has(b) && STOP.has(c)) continue;
          const k3 = `${a} ${b} ${c}`;
          trigramCounts.set(k3, (trigramCounts.get(k3) || 0) + 1);
        }
      }
    }
  }
  // Score each phrase by raw count × an information-density weight.
  // Phrases made entirely of low-info words ("want to", "can you")
  // get a 70% haircut so they don't dominate the list just because
  // English speakers all repeat the same auxiliaries. Domain words
  // ("ship it", "fix the bug", "render the chart") survive at full
  // weight and bubble up even at lower raw counts.
  //
  // Tunable: 1.0 = no penalty, 0.0 = phrase ignored entirely.
  const LOW_INFO = new Set([
    // Stopwords are already in STOP; this layer is for the next tier
    // up: high-frequency auxiliaries / generic verbs that form most
    // English filler. Keep nouns + adjectives OUT — those carry signal.
    "can","cant","could","may","might","must","should","shall","will","would",
    "want","wants","wanted","need","needs","needed",
    "make","makes","made","take","takes","took","get","gets","got",
    "do","does","did","done","go","goes","went","gone","come","came",
    "let","lets","see","saw","seen","look","looked","looks",
    "know","knows","knew","known","think","thought","tell","told","said",
    "say","says","use","uses","used","try","tries","tried",
    "find","found","keep","kept","put","help","helped",
    "sure","just","like","also","then","now","still","really","very","too",
    "first","next","last","new","old","good","bad","right","wrong","fine",
  ]);
  function phraseWeight(phrase) {
    const words = phrase.split(" ");
    const lowInfoHits = words.reduce(
      (n, w) => n + (LOW_INFO.has(w) || STOP.has(w) ? 1 : 0),
      0
    );
    // 0 low-info words → weight 1.0 (full credit, domain phrase)
    // 1 low-info word  → weight 0.6 (one anchor word, partial credit)
    // 2 low-info words → weight 0.35
    // 3 low-info words → weight 0.25
    if (lowInfoHits === 0) return 1.0;
    if (lowInfoHits === 1) return 0.6;
    if (lowInfoHits === 2) return 0.35;
    return 0.25;
  }

  // Top-N for both bigrams and trigrams, weighted. Trigrams read
  // better as "phrases" (more specific) so we lean on them when they
  // have comparable weighted-score.
  const scoreBigram = ([phrase, count]) => ({
    phrase, count, n: 2, weight: phraseWeight(phrase), score: count * phraseWeight(phrase),
  });
  const scoreTrigram = ([phrase, count]) => ({
    phrase, count, n: 3, weight: phraseWeight(phrase), score: count * phraseWeight(phrase),
  });
  const sortedBigrams = [...bigramCounts.entries()].map(scoreBigram).sort((a, b) => b.score - a.score);
  const sortedTrigrams = [...trigramCounts.entries()].map(scoreTrigram).sort((a, b) => b.score - a.score);
  // Merge: trigrams whose weighted score is at least 0.5x top bigram
  // are promoted into the favorite list; otherwise bigrams dominate.
  const topBigramScore = sortedBigrams[0]?.score || 0;
  const merged = [
    ...sortedTrigrams.filter((t) => t.score >= topBigramScore * 0.5),
    ...sortedBigrams,
  ]
    .sort((a, b) => b.score - a.score)
    .slice(0, 5)
    .map(({ phrase, count, n }) => ({ phrase, count, n }));
  const favoritePhrase = merged[0] || null;

  const sortedFrustration = [...frustrationCounts.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5)
    .map(([phrase, count]) => ({ phrase, count }));
  const topFrustration = sortedFrustration[0] || null;

  return {
    top_models: topModel.map((r) => ({ model: r.model, count: Number(r.n) })),
    peak_hour: peakHour[0] ? Number(peakHour[0].h) : null,
    peak_hour_count: peakHour[0] ? Number(peakHour[0].n) : 0,
    top_project: topProject[0]?.cwd || null,
    top_project_turns: topProject[0] ? Number(topProject[0].n) : 0,
    favorite_phrase: favoritePhrase,
    favorite_phrases: merged,
    most_frustrating_phrase: topFrustration,
    frustrating_phrases: sortedFrustration,
    avg_turns_per_session: sessionStats[0]?.avg_turns
      ? Math.round(Number(sessionStats[0].avg_turns) * 10) / 10
      : 0,
    top_correction_phrase: topFrustration,
  };
}
