import { chromium } from "playwright";
const browser = await chromium.launch();
const page = await (await browser.newContext({ viewport: { width: 1440, height: 2100 } })).newPage();
const errs = [];
page.on("pageerror", (e) => errs.push("PE: " + e.message));
page.on("console", (m) => { if (m.type() === "error") errs.push("CE: " + m.text()); });
await page.goto("http://127.0.0.1:4210", { waitUntil: "domcontentloaded", timeout: 60000 });
await page.waitForTimeout(2500);
await page.getByRole("button", { name: /^Crazy/ }).first().click();
await page.waitForTimeout(15000);
console.log("Swear-o-meter title:", await page.getByText("Swear-o-meter").count());
console.log("Mild grumble:", await page.getByText(/Mild grumble/).count());
console.log("Real complaint:", await page.getByText(/Real complaint/).count());
console.log("Full f-bomb:", await page.getByText(/Full f-bomb/).count());
console.log('"fuck" pill:', await page.getByText(/"fuck"/).count());
await page.screenshot({ path: "/tmp/sa-qa/crazy-swear.png", fullPage: true });
console.log("ERRORS:", errs.length);
errs.slice(0,5).forEach(e=>console.log(' ',e));
await browser.close();
